### ISSUE TITLE
Table-1 of article 

### ISSUE THREAD

**Issue by amirhamidihd** [facebookresearch/augmentation-corruption#3]
Hi,
 How can I reproduce the result of table-1 of article with this code?

**Comment by ericmintun** [comment]
Thanks for your interest. The scripts in `experiments/scripts/training` provide the parameters for training the models in Table 1. These scripts will also evaluate on ImageNet-C after training. The models can then be tested on ImageNet-Cbar using `test_imagenet_cbar.sh` and `test_cifar_cbar.sh` in `experiments/scripts`. To run these you will need to configure hydra and submitit for your own computing resources by putting a configuration file in `experiments/conf/hydra/launcher` and pointing the related environment variable in the scripts at this configuration.
